export const INPUT_SUCESS = "INPUT_SUCESS";
export const INPUT_FAILURE = "INPUT_FAILURE";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_FAIL = "SESSION_FAIL"
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAIL = "MESSAGE_FAIL";
export const SESSION_ACTIVE = "SESSION_ACTIVE"